### ISSUE TITLE
Devtools break with Preact + Next.js + Tailwind - "Connected, waiting for nodes to load..."

### ISSUE THREAD

**Issue by sw-yx** [preactjs/preact-devtools#111]
hi! I have no idea what is broken so pardon the driveby issue filing but I reckon this might be an opportunity for you to make the devtools more robust... here goes.

here's the repo I'm running: https://github.com/sw-yx/smaller-safer-serverless-starter

It builds ontop of @developit's https://github.com/developit/nextjs-preact-demo/ demo, and then adds the standard Tailwind tooling via PostCSS. As far as I can tell, standard PostCSS operation shouldnt impact Preact at all, but somehow it does, because it breaks the Devtools:

![image](https://user-images.githubusercontent.com/6764957/78422716-edcb1180-7693-11ea-9fbd-b07159e73edf.png)

I've tested Jason's demo and it works with devtools, therefore it's definitely something to do with Tailwind/PostCSS and Preact interacting in some weird way. Want to take a look?

**Comment by marvinhagemeister** [comment]
@sw-yx That's awesome, thank you so much for making a bug report and giving us a chance to make Preact even better :+1: 

Just checked out the repo but the code in the `master` branch doesn't seem to use Preact at all. The whole app is rendered with React and their devtools connect successfully. On top of that the `next.config.js` forces webpack to bundle `preact/debug` and `preact` but it isn't used anywhere.

Maybe you forgot to push some code?

Although Preact is not used to render the page, `preact/debug` will immediately establish a connection to the devtools. But because the page is rendered with React and not Preact, it won't progress further as no nodes will be sent to the devtools.

It's on the roadmap to make the message more detailed and introduce new ones to make it more obvious what's happening.

**Comment by sw-yx** [comment]
ohh oops i accidentally swapped out the package.json aliases when trying to install Storybook - my bad, let me retry

**Comment by sw-yx** [comment]
I can confirm that reinstalling preact as an alias of react solved the issue. I made a really dumb mistake and didn't know that i had accidentally overridden it when I copied instructions.

 So sorry for the trouble!!!!

**Comment by marvinhagemeister** [comment]
No worries, happens to all of us (myself included)! Thanks again for reaching out :slightly_smiling_face:

**Comment by sw-yx** [comment]
it's still interesting that the Preact Devtools recognized Preact even tho Preact wasnt being used. maybe we can tighten up that detection logic, and/or say "hey idiot you're using react"
