### ISSUE TITLE
ChromeExtention works not correctly

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [preactjs/preact-devtools#144]
ChromeExtention works not correctly. 
I don’t know how to describe it in words, so I recorded a video:

https://mega.nz/file/1opVRB4T#nhRyKEd1dGwEHxCs3ksL7ETdEeXSM9iu23FBDbPI46A

**Comment by marvinhagemeister** [comment]
This is awesome, thank you so much for reporting those! The video is excellent and shows perfectly what the issues are :+1:

Fixed the first two of the presented issues this morning. The last one is a little more involved, but it's doable. Will take a look at the weekend :100: 

1. [x] Only first DOM node of `Fragments` highlighted - fixed with #146 
2. [x] Highlight overlay stuck on scroll - fixed with #147
3. [ ] Hovering/Clicking on the right hand side of element names in the Elements panel does not work

**Comment by marvinhagemeister** [comment]
Alright, just fixed the last one! A new release will follow soon :tada:
