### ISSUE TITLE
Highlight updates crash with iframes

### ISSUE THREAD

**Issue by wnayes** [preactjs/preact-devtools#236]
When the "Highlight updates" functionality is enabled, there is the potential for an error in multiple window scenarios.

The [`updateHighlight`](https://github.com/preactjs/preact-devtools/blob/dbdbef9c57b43653ac9956591dfc980f65daab37/src/adapter/10/renderer.ts#L127) function checks `instanceof Text` to determine if a node is a text node. However, this check fails in the scenario where the devtools script is in one window and the rendered content is in another (iframe). Downstream, this leads to a crash trying to execute `dom.getBoundingClientRect()` in `measureUpdate` on a text node that failed this check.

I think checking `nodeType === 3 (Node.TEXT_NODE)` is a robust way to handle text elements from other windows in this case.

**Comment by marvinhagemeister** [comment]
I'm curious if you did run into this error, because as is the nodes of the different frames won't leak to each other. Each frame (iframes + page) will be injected with their own devtools hook and those have no knowledge of the other ones. They all talk directly with the extension through the background script.

So the scenario you're describing should not be possible in theory, unless you've discovered an actual bug with the way the injection is done. Can you share more details about the error?

> I think checking nodeType === 3 (Node.TEXT_NODE) is a robust way 

Agree, that's a better way to check for Text nodes 👍

**Comment by wnayes** [comment]
I think this only becomes reproducible with this [preact PR](https://github.com/preactjs/preact/pull/2569) that changes the `document` used for element creation, which I have been patching in myself since it is not part of the official release. With that PR, preact creates elements using the `ownerDocument` of the render root element. Without that PR, preact always uses `document.createTextNode` and I think that masks the issue.

With that PR applied, something like this code sandbox should reproduce it.

https://codesandbox.io/s/highlight-iframetest-qj41u-qj41u
